In [84]:
import re #Regular Expression/REGEX
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [85]:
xl_file = pd.ExcelFile('Regex Interview Set.xlsx')
dfs = {sheet_name: xl_file.parse(sheet_name) 
          for sheet_name in xl_file.sheet_names}
data = dfs['Sheet1']

In [86]:
data.head(5)

Content  \
0         Yth Bpk/Ibu kntrk kredit Anda sdh jth tmpo   
1  Tagihan KreditPikachu Rp136.680,0 terlambat ba...   
2  NasabahYth, KK MasterCard Gold anda tlh jatuh ...   
3  Byr lunas hr ini Rp1600000 agar denda tidak be...   
4  Tagihan KreditRaichu Rp777.000,0 terlambat bay...   

                                             Comment Expected Label  
0       Sudah jatuh tempo, berarti layak kena label.           LATE  
1         Terlambat bayar, berarti layak kena label.           LATE  
2       Telah jatuh tempo, berarti layak kena label.           LATE  
3  Karena perlu membayar hari ini agar denda tida...           LATE  
4         Terlambat bayar, berarti layak kena label.           LATE

In [87]:
korpus=[]
for i in range(0,len(data)):
    review = re.sub('[^a-zA-Z]', ' ',data.iloc[i,0])
    review = review.lower()
    korpus.append(review)
    
data['Content'] = korpus

In [88]:
korpus=[]
for i in range(0,len(data)):
    review = re.sub('\s\w\s\w+',' masuk',data.iloc[i,0])
    
    review = re.sub('kntrk', ' kontrak ' ,review)
    review = re.sub('sdh', ' sudah ' ,review)
    review = re.sub('jth', ' jatuh ' ,review)
    review = re.sub('tmpo', ' tempo ' ,review)
    
    review = re.sub('\w*ingat\w*',' ingat ',review)
    review = re.sub('\w*hindar\w*',' hindar ',review)
    review = re.sub('\w*utk\w*', 'untuk ',review)
    review = re.sub('\w*t+m+b+\w*',' tambah ',review)
    review = re.sub('\w*sgr\w*',' segera ',review)
    review = re.sub('\w*angsur\w*',' angsuran ',review)
    
    review = re.sub('\srp\s',' rupiah ',review)
    review = re.sub('(\w*kredit)',' kredit ',review)
    review = re.sub('nasabah',' nasabah ',review)
    review = re.sub('tlh',' telah ',review)
    review = re.sub('\skk\s',' kartu kredit ',review)
    review = re.sub('\spd\s',' pada ',review)
    
    review = re.sub('\w*tambah\w*',' tambah ',review)
    review = re.sub('\w*panjang\w*',' panjang ',review)
    review = re.sub('\s+hr\s+',' hari ',review)
    
    review = re.sub('raichu', ' pickachu' ,review)
    review = re.sub('\w*lambat\w*',' lambat ' ,review)
    
    review = re.sub('\w*bayar\w*',' bayar ' ,review)
    
    #6
    review = re.sub('\w*gmn\w*', ' gimana ' ,review)
    review = re.sub('\w*pika\w*',' pikachu ' ,review)
    review = re.sub('\w*uang\w*',' uang ' ,review)
    
    review = re.sub('\w*belum\w*', ' belum ' ,review)
    
    review = re.sub('\w*tgl\w*', ' tanggal ' ,review)
    review = re.sub('\w*sambung\w*',' sambung ' ,review)
    
    review = re.sub('\w*bpk\w*', ' bpk ' ,review)
    review = re.sub('\sama\s', ' sama ' ,review)
    
    review = re.sub('akn', ' akan ' ,review)
    
    review = re.sub('\ssy\s', ' saya ' ,review)
    
    review = re.sub('masukkan', ' masuk ' ,review)
    review = re.sub('dgn', ' dengan ' ,review)
    
    review = re.sub('bpk', ' bapak ' ,review)
    review = re.sub('telpun', ' telepon ' ,review)
    review = re.sub('\s*byr\s*',' bayar ',review)
    #NEW
    review = re.sub('\w*guna\w*',' guna ' ,review)
    review = re.sub('\w*karena\w*',' karena ' ,review)
    review = re.sub('\w*harga\w*',' harga ' ,review)
    review = re.sub('\w*hubung\w*',' hubung ' ,review)
    review = re.sub('\w*unggu\w*',' tunggu ' ,review)

    review = re.sub('\w*cek\w*',' cek ' ,review)
    review = re.sub('pickachu',' pikachu ' ,review)

    review = re.sub('\w*pok\smon\w*',' pokemon ' ,review)\

    review = re.sub('\w*yg\w*',' yang ' ,review)
    review = re.sub('\s\s+',' ',review)
    korpus.append(review)
    
data['Content'] = korpus    

In [89]:
# cek apakah 2 huruf itu adalah kata yang penting
cekkorpus=[]
for i in range(0,len(data)):
    
    regex_num = re.compile('\s\w{1,2}\s') 
    tigahuruf =  regex_num.findall(data.iloc[i,0])
    
    cekkorpus.append(tigahuruf)
cekkorpus

[[],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [' ke '],
 [],
 [],
 [' di ', ' di ', ' di '],
 [],
 [],
 [],
 [],
 [' tv ', ' ly '],
 [' ke '],
 [],
 [' ke ']]

In [90]:
newkorpus=[]
for i in range(0,len(data)):
    review = re.sub('\s\w{1,2}\s','',data.iloc[i,0])
    
    review = re.sub('\s\s+',' ',review)
    newkorpus.append(review)
    
data['Content'] = newkorpus   

In [91]:
# cek apakah 3 huruf itu adalah kata yang penting
cekkorpus=[]
for i in range(0,len(data)):
    
    regex_num = re.compile('\s\w{1,3}\s') 
    tigahuruf =  regex_num.findall(data.iloc[i,0])
    
    cekkorpus.append(tigahuruf)
cekkorpus
#lumayan. let it be

[[' ibu '],
 [],
 [' yth '],
 [' ini '],
 [],
 [],
 [' ibu ', ' ini '],
 [' ibu '],
 [],
 [],
 [],
 [' ini ', ' mau ', ' kan ', ' ini ', ' yah ', ' mau ', ' nya ', ' mau '],
 [' gak ', ' kok ', ' non ', ' non '],
 [' ibu ', ' bni '],
 [],
 [' pak '],
 [' bbq ', ' des '],
 [' ini ', ' ada ', ' cek '],
 [],
 [' sms ', ' sms ']]

# CLASSIFICATION

In [92]:
data['label'] = 0
for i in np.arange(len(data)):
    if data.iloc[i,2] == 'LATE':
        data.iloc[i,3] = 1
    else:
        data.iloc[i,3] = 0

In [93]:
from sklearn.metrics import accuracy_score
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=110)

corpus = list(data['Content'])

X = cv.fit_transform(corpus).toarray()
y = data.iloc[:,3:4].values

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=0)

# modelling

In [102]:
from sklearn.linear_model import LogisticRegression
logs = LogisticRegression()
b_model = logs.fit(X_train, y_train)

b_pred = b_model.predict(X_test)
b_acc = accuracy_score(y_test, b_pred)
print("akurasi Logistic Regression:", b_acc)

cm = confusion_matrix(y_test, b_pred)

print("Confusion Matrix LogReg:")
print(cm)

akurasi Logistic Regression: 1.0
Confusion Matrix LogReg:
[[3 0]
 [0 1]]


In [95]:
from sklearn.svm import SVC
logs = SVC(kernel='linear',)
b_model = logs.fit(X_train, y_train)

b_pred = b_model.predict(X_test)
b_acc = accuracy_score(y_test, b_pred)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, b_pred)

print("akurasi SVC:", b_acc)
print("Confusion Matrix SVC:")
print(cm)

akurasi SVC: 1.0
Confusion Matrix SVC:
[[3 0]
 [0 1]]


In [96]:
from sklearn.tree import DecisionTreeClassifier
logs = DecisionTreeClassifier(criterion='entropy',)
b_model = logs.fit(X_train, y_train)

b_pred = b_model.predict(X_test)
b_acc = accuracy_score(y_test, b_pred)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, b_pred)

print("akurasi DecisionTree:", b_acc)
print("Confusion Matrix DecisionTree:")
print(cm)

akurasi DecisionTree: 1.0
Confusion Matrix DecisionTree:
[[3 0]
 [0 1]]
